AWSTemplateFormatVersion: "2010-09-09"
Description: This stack deploys the infrastructure for our web application

Resources:
  WebApplicationEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: udacity-key-pair
      ImageId: ami-064d33fad222a1c4a
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebApplicationSecurityGroup
      Tags:
        - Key: Name
          Value: Ansible-CICD-Webserver

  WebApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
