version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create infrastructure with AWS cloud formation"
          command: |
            aws cloudformation deploy --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --template-file ./cloudformation/server.yml
workflows:
  ansible:
    jobs:
      - create_infrastructure
