---
- name: "update apt packages"
  become: yes
  yum:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  yum:
    upgrade: yes

- name: "remove unneeded packages"
  become: yes
  yum:
    autoremove: yes

- name: "install dependencies"
  become: yes
  yum:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create directories"
  file:
    path: ~/web
    state: directory

- name: "copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Executing node"
  shell: |
    pm2 start ~/web/index.js -f
